GOOGLE_GEOCODING_API_KEY = "AIzaSyDKPnMXJV96VTiDA9Bdfll18tUfmWAbV84"   # Sunucu için, IP-restricted
GOOGLE_MAPS_JS_API_KEY = "AIzaSyBwuTfhPZ5l4SD20v_Op_g7JIJFsQ0ABbo"    # Tarayıcı için, HTTP referrer-restricted
